unit uJigFiles;

{ The jigs the program carries - jigs/ in the repository.

  Generated by jigs/make-jigs.pas - do not edit this by hand, edit the jig
  and run that again. }

{$mode objfpc}{$H+}

interface

uses
  Classes;

function JigFileCount: Integer;
function JigFileName(I: Integer): string;
procedure JigFileLines(I: Integer; L: TStrings);

implementation

function JigFileCount: Integer;
begin
  Result := 5;
end;

function JigFileName(I: Integer): string;
begin
  case I of
    0: Result := 'star.pas';
    1: Result := 'balloon.py';
    2: Result := 'fence.pl';
    3: Result := 'steps.sh';
    4: Result := 'steps.ps1';
  else
    Result := '';
  end;
end;

procedure Jig0(L: TStrings);
begin
  L.Add('#!/usr/bin/env instantfpc');
  L.Add('{ A JIG: any program that prints Heck.  This one prints a star.');
  L.Add('  It is handed its values as  Name=value  - lengths as plain inches. }');
  L.Add('program star;');
  L.Add('{$mode objfpc}{$H+}');
  L.Add('uses SysUtils, Math;');
  L.Add('');
  L.Add('function Value(const Name: string; Default: Double): Double;');
  L.Add('var I: Integer; S: string;');
  L.Add('begin');
  L.Add('  Result := Default;');
  L.Add('  for I := 1 to ParamCount do');
  L.Add('  begin');
  L.Add('    S := ParamStr(I);');
  L.Add('    if SameText(Copy(S, 1, Length(Name) + 1), Name + ''='') then');
  L.Add('      Result := StrToFloatDef(Copy(S, Length(Name) + 2, 99), Default);');
  L.Add('  end;');
  L.Add('end;');
  L.Add('');
  L.Add('var');
  L.Add('  N, I: Integer;');
  L.Add('  R, E, No, A, Rad: Double;');
  L.Add('  X, Y: array of Double;');
  L.Add('begin');
  L.Add('  DefaultFormatSettings.DecimalSeparator := ''.'';');
  L.Add('  N  := Round(Value(''Points'', 5));');
  L.Add('  R  := Value(''Radius'', 24);');
  L.Add('  E  := Value(''East'', 0);');
  L.Add('  No := Value(''North'', 0);');
  L.Add('  SetLength(X, 2 * N);');
  L.Add('  SetLength(Y, 2 * N);');
  L.Add('  for I := 0 to 2 * N - 1 do');
  L.Add('  begin');
  L.Add('    if Odd(I) then Rad := R * 0.4 else Rad := R;');
  L.Add('    A := Pi / 2 + I * Pi / N;');
  L.Add('    X[I] := E + Rad * Cos(A);');
  L.Add('    Y[I] := No + Rad * Sin(A);');
  L.Add('  end;');
  L.Add('  for I := 0 to 2 * N - 1 do');
  L.Add('    WriteLn(Format(''line = %.4f" east, %.4f" north, 0 up to %.4f" east, %.4f" north, 0 up'',');
  L.Add('      [X[I], Y[I], X[(I + 1) mod (2 * N)], Y[(I + 1) mod (2 * N)]]));');
  L.Add('end.');
end;

procedure Jig1(L: TStrings);
begin
  L.Add('#!/usr/bin/env python3');
  L.Add('# A JIG: any program that prints Heck.  This one prints a balloon on a string.');
  L.Add('# It is handed its values as  Name=value  - lengths as plain inches.');
  L.Add('import sys, math');
  L.Add('');
  L.Add('v = dict(a.split("=", 1) for a in sys.argv[1:] if "=" in a)');
  L.Add('r = float(v.get("Radius", 18))');
  L.Add('e = float(v.get("East", 0))');
  L.Add('n = float(v.get("North", 0))');
  L.Add('h = float(v.get("Height", 72))');
  L.Add('');
  L.Add('# the balloon: a circle standing up, facing south');
  L.Add('print("circle")');
  L.Add('print(f"  center = {e}\" east, {n}\" north, {h}\" up")');
  L.Add('print(f"  radius = {r}\"")');
  L.Add('print("  facing = south")');
  L.Add('print("  ink = red")');
  L.Add('print("end")');
  L.Add('');
  L.Add('# the knot: a little triangle under it');
  L.Add('k = r / 8');
  L.Add('top = h - r');
  L.Add('print(f"line = {e}\" east, {n}\" north, {top}\" up to {e - k}\" east, {n}\" north, {top - k}\" up")');
  L.Add('print(f"line = {e - k}\" east, {n}\" north, {top - k}\" up to {e + k}\" east, {n}\" north, {top - k}\" up")');
  L.Add('print(f"line = {e + k}\" east, {n}\" north, {top - k}\" up to {e}\" east, {n}\" north, {top}\" up")');
  L.Add('');
  L.Add('# the string: a gentle wave down to the floor');
  L.Add('steps = 12');
  L.Add('x0, z0 = e, top - k');
  L.Add('for i in range(1, steps + 1):');
  L.Add('    z1 = (top - k) * (1 - i / steps)');
  L.Add('    x1 = e + math.sin(i * math.pi / 3) * r / 6');
  L.Add('    print(f"line = {x0:.4f}\" east, {n}\" north, {z0:.4f}\" up to {x1:.4f}\" east, {n}\" north, {z1:.4f}\" up")');
  L.Add('    x0, z0 = x1, z1');
end;

procedure Jig2(L: TStrings);
begin
  L.Add('#!/usr/bin/env perl');
  L.Add('# A JIG: any program that prints Heck.  This one prints a fence.');
  L.Add('# It is handed its values as  Name=value  - lengths as plain inches.');
  L.Add('use strict; use warnings;');
  L.Add('my %v = map { /^(\w+)=(.*)$/ ? ($1 => $2) : () } @ARGV;');
  L.Add('my $posts   = $v{Posts}   // 6;');
  L.Add('my $spacing = $v{Spacing} // 24;');
  L.Add('my $height  = $v{Height}  // 36;');
  L.Add('my $north   = $v{North}   // 0;');
  L.Add('my $east    = $v{East}    // 0;');
  L.Add('');
  L.Add('for my $i (0 .. $posts - 1) {');
  L.Add('    my $x = $east + $i * $spacing;');
  L.Add('    print qq{line = $x" east, $north" north, 0 up to + $height" up\n};');
  L.Add('}');
  L.Add('my $end = $east + ($posts - 1) * $spacing;');
  L.Add('for my $rail ($height * 0.3, $height * 0.8) {');
  L.Add('    print qq{line = $east" east, $north" north, $rail" up to $end" east, $north" north, $rail" up\n};');
  L.Add('}');
end;

procedure Jig3(L: TStrings);
begin
  L.Add('#!/bin/sh');
  L.Add('# A JIG: any program that prints Heck.  This one prints a flight of steps.');
  L.Add('# It is handed its values as  Name=value  - lengths as plain inches.');
  L.Add('# (steps.ps1 beside this is the same jig for a machine with PowerShell and');
  L.Add('# no shell; the program runs whichever suits the machine it is on.)');
  L.Add('awk -v args="$*" ''BEGIN {');
  L.Add('  n = split(args, A, " ")');
  L.Add('  for (i = 1; i <= n; i++) { split(A[i], kv, "="); v[kv[1]] = kv[2] }');
  L.Add('  steps = (v["Steps"] != "") ? v["Steps"] : 5');
  L.Add('  rise  = (v["Rise"]  != "") ? v["Rise"]  : 7.5');
  L.Add('  going = (v["Run"]   != "") ? v["Run"]   : 10');
  L.Add('  wide  = (v["Width"] != "") ? v["Width"] : 36');
  L.Add('  e     = (v["East"]  != "") ? v["East"]  : 0');
  L.Add('  no    = (v["North"] != "") ? v["North"] : 0');
  L.Add('  x = e; z = 0');
  L.Add('  for (side = 0; side <= 1; side++) {');
  L.Add('    y = no + side * wide; x = e; z = 0');
  L.Add('    for (i = 1; i <= steps; i++) {');
  L.Add('      printf "line = %g\" east, %g\" north, %g\" up to + %g\" up\n", x, y, z, rise');
  L.Add('      printf "line = %g\" east, %g\" north, %g\" up to + %g\" east\n", x, y, z + rise, going');
  L.Add('      x += going; z += rise');
  L.Add('    }');
  L.Add('  }');
  L.Add('  x = e; z = 0');
  L.Add('  printf "line = %g\" east, %g\" north, %g\" up to + %g\" north\n", x, no, z, wide');
  L.Add('  for (i = 1; i <= steps; i++) {');
  L.Add('    printf "line = %g\" east, %g\" north, %g\" up to + %g\" north\n", x, no, z + rise, wide');
  L.Add('    printf "line = %g\" east, %g\" north, %g\" up to + %g\" north\n", x + going, no, z + rise, wide');
  L.Add('    x += going; z += rise');
  L.Add('  }');
  L.Add('}''');
end;

procedure Jig4(L: TStrings);
begin
  L.Add('# A JIG: any program that prints Heck.  This one prints a flight of steps.');
  L.Add('# It is handed its values as  Name=value  - lengths as plain inches.');
  L.Add('# (steps.sh beside this is the same jig for a machine with a shell and no');
  L.Add('# PowerShell; the program runs whichever suits the machine it is on.)');
  L.Add('$v = @{}');
  L.Add('foreach ($a in $args) { if ($a -match ''^(\w+)=(.*)$'') { $v[$matches[1]] = $matches[2] } }');
  L.Add('function Val($name, $default) {');
  L.Add('  if ($v.ContainsKey($name)) { [double]::Parse($v[$name], [cultureinfo]::InvariantCulture) } else { $default }');
  L.Add('}');
  L.Add('function N($x) { ([double]$x).ToString(''0.####'', [cultureinfo]::InvariantCulture) }');
  L.Add('');
  L.Add('$steps = [int](Val ''Steps'' 5)');
  L.Add('$rise  = Val ''Rise'' 7.5');
  L.Add('$going = Val ''Run'' 10');
  L.Add('$wide  = Val ''Width'' 36');
  L.Add('$e     = Val ''East'' 0');
  L.Add('$no    = Val ''North'' 0');
  L.Add('');
  L.Add('foreach ($side in 0, 1) {');
  L.Add('  $y = $no + $side * $wide; $x = $e; $z = 0');
  L.Add('  for ($i = 1; $i -le $steps; $i++) {');
  L.Add('    "line = $(N $x)`" east, $(N $y)`" north, $(N $z)`" up to + $(N $rise)`" up"');
  L.Add('    "line = $(N $x)`" east, $(N $y)`" north, $(N ($z + $rise))`" up to + $(N $going)`" east"');
  L.Add('    $x += $going; $z += $rise');
  L.Add('  }');
  L.Add('}');
  L.Add('$x = $e; $z = 0');
  L.Add('"line = $(N $x)`" east, $(N $no)`" north, $(N $z)`" up to + $(N $wide)`" north"');
  L.Add('for ($i = 1; $i -le $steps; $i++) {');
  L.Add('  "line = $(N $x)`" east, $(N $no)`" north, $(N ($z + $rise))`" up to + $(N $wide)`" north"');
  L.Add('  "line = $(N ($x + $going))`" east, $(N $no)`" north, $(N ($z + $rise))`" up to + $(N $wide)`" north"');
  L.Add('  $x += $going; $z += $rise');
  L.Add('}');
end;

procedure JigFileLines(I: Integer; L: TStrings);
begin
  case I of
    0: Jig0(L);
    1: Jig1(L);
    2: Jig2(L);
    3: Jig3(L);
    4: Jig4(L);
  end;
end;

end.
