program makemannequin;

{ A mannequin: one group, made by the body jig.

  Nothing here draws.  The drawing is what jigs/body.py prints for a woman
  six foot tall and a hundred and fifty pounds, read in exactly as the
  program reads a jig's output, and saved with the jig line kept on the
  group - so that right-clicking her and running the jig again with other
  numbers gives another body.  She is there to be dressed: the reason for
  her is the fabric that is not drawn yet.

  Run it to write examples/mannequin.hsk and ../uExMannequin.pas:
      cd examples
      fpc -Mobjfpc -Sh -Fu.. make-mannequin.pas && ./makemannequin

  It runs the jig with python3, so that has to be on the machine.

  Copyright (c) 2021-2026 Noella Stone - MIT, see LICENSE. }

{$mode objfpc}{$H+}

uses
  SysUtils, Classes, Math, Types, Process, Graphics, uWork, uHeck;

const
  { the jig line as it stands on the group - inches to the jig itself }
  SPEC = '''body'' with Height = 6'', Weight = 150';
  ART_W = 1200; ART_H = 760;
  PIECE = 2000;

var
  D: TWorkDoc;
  Out_, U, Printed: TStringList;
  Body: string;
  I, G, ErrLine, F, N, P, NParts: Integer;
  Err: string;
  BLo, BHi, CamMid, SLo, SHi: TP3;
  CamV: TProjector;
  CamP: TPointF;
  BaseP, CamZoom: Double;
begin
  D := TWorkDoc.Create;
  Out_ := TStringList.Create;
  Printed := TStringList.Create;
  try
    if not RunCommand('python3', ['../jigs/body.py', 'Height=72', 'Weight=150'], Body,
      [poUsePipes, poStderrToOutPut]) then
    begin
      WriteLn('the jig did not run: ', Copy(Body, 1, 300));
      Halt(1);
    end;
    Printed.Text := Body;

    { the group, with its jig line, and the jig's things inside it - the
      way the program does it when it runs one }
    G := D.NewPart('Mannequin', 0);
    D.SetPartJig(G, SPEC);
    D.Stamp := G;
    if not ReadHeck(Printed, D, usImperial, ErrLine, Err) then
    begin
      WriteLn(Format('what the jig printed is not Heck.  Line %d: %s', [ErrLine + 1, Err]));
      Halt(1);
    end;
    D.Stamp := 0;

    { --- out it goes -------------------------------------------------- }
    BaseP := PixelsPerUnit(usImperial, ScaleTable(usImperial, 2), 96);
    D.Bounds(BLo, BHi);
    { aimed a little above her middle: a window shorter than the one this
      fits for loses the bottom first, and feet matter less than a face }
    CamMid := P3((BLo.X + BHi.X) / 2, (BLo.Y + BHi.Y) / 2, BLo.Z + (BHi.Z - BLo.Z) * 0.58);
    CamV.Kind := vkOrbit;
    CamV.Az := -0.75;
    CamV.El := 0.12;
    CamV.Ppu := 1; CamV.OX := 0; CamV.OY := 0;
    SLo := P3(1E30, 1E30, 0); SHi := P3(-1E30, -1E30, 0);
    for I := 0 to 7 do
    begin
      CamP := Project(CamV, P3(
        specialize IfThen<Double>((I and 1) = 0, BLo.X, BHi.X),
        specialize IfThen<Double>((I and 2) = 0, BLo.Y, BHi.Y),
        specialize IfThen<Double>((I and 4) = 0, BLo.Z, BHi.Z)));
      SLo.X := Min(SLo.X, CamP.X); SHi.X := Max(SHi.X, CamP.X);
      SLo.Y := Min(SLo.Y, CamP.Y); SHi.Y := Max(SHi.Y, CamP.Y);
    end;
    { fitted to the height with room under her feet: a standing figure is
      all height, and the sheet's canvas is not the whole of the window }
    CamZoom := Min((ART_W * 0.86) / ((SHi.X - SLo.X) * BaseP),
                   (ART_H * 0.5) / ((SHi.Y - SLo.Y) * BaseP));
    CamV.Ppu := BaseP * CamZoom;
    CamP := Project(CamV, CamMid);

    Out_.Add('HECKERS-SKETCH 1');
    Out_.Add('SHEET Mannequin');
    Out_.Add('UNITS 0');
    Out_.Add('SCALE 2');
    Out_.Add('SNAP 1');
    Out_.Add('VIEW 2');
    Out_.Add(StringReplace(Format('CAMERA %.6f %.6f %.6f %.3f %.3f',
      [CamV.Az, CamV.El, CamZoom, ART_W / 2 - CamP.X, ART_H / 2 - CamP.Y]),
      DefaultFormatSettings.DecimalSeparator, '.', [rfReplaceAll]));
    D.SaveTo(Out_);
    Out_.Add('ENDSHEET');
    Out_.SaveToFile('mannequin.hsk');

    U := TStringList.Create;
    U.Add('unit uExMannequin;');
    U.Add('');
    U.Add('{ The mannequin example.');
    U.Add('');
    U.Add('  Generated by examples/make-mannequin.pas - do not edit this by hand,');
    U.Add('  edit that, or the body jig, and run it again.  It is the same');
    U.Add('  drawing as examples/mannequin.hsk, carried inside the program so');
    U.Add('  that a portable build is one file and the examples folder can be');
    U.Add('  written out beside it on a machine that has never seen one. }');
    U.Add('');
    U.Add('{$mode objfpc}{$H+}');
    U.Add('');
    U.Add('interface');
    U.Add('');
    U.Add('uses');
    U.Add('  Classes;');
    U.Add('');
    U.Add('{ The mannequin, as the lines of a .hsk file. }');
    U.Add('procedure MannequinDrawing(L: TStrings);');
    U.Add('');
    U.Add('implementation');
    U.Add('');
    { seventeen thousand lines in one procedure is more than the compiler
      will take - "too many registers" - so it goes in pieces }
    NParts := (Out_.Count + PIECE - 1) div PIECE;
    for P := 0 to NParts - 1 do
    begin
      U.Add(Format('procedure Piece%d(L: TStrings);', [P]));
      U.Add('begin');
      for I := P * PIECE to Min(Out_.Count, (P + 1) * PIECE) - 1 do
        U.Add('  L.Add(' + QuotedStr(Out_[I]) + ');');
      U.Add('end;');
      U.Add('');
    end;
    U.Add('procedure MannequinDrawing(L: TStrings);');
    U.Add('begin');
    for P := 0 to NParts - 1 do
      U.Add(Format('  Piece%d(L);', [P]));
    U.Add('end;');
    U.Add('');
    U.Add('end.');
    U.SaveToFile('../uExMannequin.pas');
    U.Free;

    F := 0; N := 0;
    for I := 0 to D.Live - 1 do
      if D[I].Kind = ekFace then Inc(F) else if D[I].Kind = ekLine then Inc(N);
    WriteLn(Format('wrote mannequin.hsk and ../uExMannequin.pas: %d faces, %d lines, %d lines of text',
      [F, N, Out_.Count]));
  finally
    Printed.Free;
    Out_.Free;
    D.Free;
  end;
end.
