#!/usr/bin/env instantfpc
{ The jigs example.

  The others in this folder are generated from nothing by their make-*.pas.
  This one cannot be: what it shows is what four jigs printed and what the
  program made of a cube typed as twelve lines, so it is made WITH the
  program - /source, Sample, Apply, Run jigs, Save - and saved here as
  jigs.hsk.  All this does is carry that file into ../uExJigs.pas so the
  program can write it out on a machine that has never seen it.

  Run it from this folder after saving a new jigs.hsk:   ./make-jigs.pas   }
program makejigsexample;
{$mode objfpc}{$H+}
uses Classes, SysUtils;
var
  U, L: TStringList;
  I: Integer;
begin
  L := TStringList.Create;
  U := TStringList.Create;
  L.LoadFromFile('jigs.hsk');
  U.Add('unit uExJigs;');
  U.Add('');
  U.Add('{ The jigs example.');
  U.Add('');
  U.Add('  Generated by examples/make-jigs.pas from examples/jigs.hsk - do not edit');
  U.Add('  this by hand.  It is the same drawing, carried inside the program so');
  U.Add('  that a portable build is one file. }');
  U.Add('');
  U.Add('{$mode objfpc}{$H+}');
  U.Add('');
  U.Add('interface');
  U.Add('');
  U.Add('uses');
  U.Add('  Classes;');
  U.Add('');
  U.Add('{ Four groups, each made by a jig, as the lines of a .hsk file. }');
  U.Add('procedure JigsDrawing(L: TStrings);');
  U.Add('');
  U.Add('implementation');
  U.Add('');
  U.Add('procedure JigsDrawing(L: TStrings);');
  U.Add('begin');
  for I := 0 to L.Count - 1 do
    U.Add('  L.Add(' + QuotedStr(L[I]) + ');');
  U.Add('end;');
  U.Add('');
  U.Add('end.');
  U.SaveToFile('../uExJigs.pas');
  WriteLn('wrote ../uExJigs.pas: ', L.Count, ' lines');
end.
