#!/usr/bin/env instantfpc
{ Turns the jigs in this folder into ../uJigFiles.pas, so that a program
  which is one file can write them out on a machine that has never seen
  them - the same trick the example drawings use.  Run it from this folder
  after changing a jig:   ./make-jigs.pas   }
program makejigs;
{$mode objfpc}{$H+}
uses Classes, SysUtils;
const
  FILES: array[0..4] of string = ('star.pas', 'balloon.py', 'fence.pl', 'steps.sh', 'steps.ps1');
var
  U, L: TStringList;
  I, K: Integer;
begin
  U := TStringList.Create;
  L := TStringList.Create;
  U.Add('unit uJigFiles;');
  U.Add('');
  U.Add('{ The jigs the program carries - jigs/ in the repository.');
  U.Add('');
  U.Add('  Generated by jigs/make-jigs.pas - do not edit this by hand, edit the jig');
  U.Add('  and run that again. }');
  U.Add('');
  U.Add('{$mode objfpc}{$H+}');
  U.Add('');
  U.Add('interface');
  U.Add('');
  U.Add('uses');
  U.Add('  Classes;');
  U.Add('');
  U.Add('function JigFileCount: Integer;');
  U.Add('function JigFileName(I: Integer): string;');
  U.Add('procedure JigFileLines(I: Integer; L: TStrings);');
  U.Add('');
  U.Add('implementation');
  U.Add('');
  U.Add('function JigFileCount: Integer;');
  U.Add('begin');
  U.Add('  Result := ' + IntToStr(Length(FILES)) + ';');
  U.Add('end;');
  U.Add('');
  U.Add('function JigFileName(I: Integer): string;');
  U.Add('begin');
  U.Add('  case I of');
  for I := 0 to High(FILES) do
    U.Add('    ' + IntToStr(I) + ': Result := ' + QuotedStr(FILES[I]) + ';');
  U.Add('  else');
  U.Add('    Result := '''';');
  U.Add('  end;');
  U.Add('end;');
  U.Add('');
  for I := 0 to High(FILES) do
  begin
    L.LoadFromFile(FILES[I]);
    U.Add('procedure Jig' + IntToStr(I) + '(L: TStrings);');
    U.Add('begin');
    for K := 0 to L.Count - 1 do
      U.Add('  L.Add(' + QuotedStr(L[K]) + ');');
    U.Add('end;');
    U.Add('');
  end;
  U.Add('procedure JigFileLines(I: Integer; L: TStrings);');
  U.Add('begin');
  U.Add('  case I of');
  for I := 0 to High(FILES) do
    U.Add('    ' + IntToStr(I) + ': Jig' + IntToStr(I) + '(L);');
  U.Add('  end;');
  U.Add('end;');
  U.Add('');
  U.Add('end.');
  U.SaveToFile('../uJigFiles.pas');
  WriteLn('wrote ../uJigFiles.pas: ', Length(FILES), ' jigs');
end.
